export const Questions = [
    {
        prompt: "What is 1+3?",
        OptionA:"24",
        OptionB:"2",
        OptionC:"4",
        OptionD:"74",
        answer:"C",
    },
    {
        prompt: "Which  is a streaming platform?",
        OptionA:"Twitter",
        OptionB:"Twitch",
        OptionC:"Google",
        OptionD:"Insta",
        answer:"B",
    },
    {
        prompt: "which is the best tool for frontend?",
        OptionA:"C++",
        OptionB:"Java",
        OptionC:"React js",
        OptionD:"Node js",
        answer:"C",
    },
    {
        prompt: "What did we create in this project?",
        OptionA:"TODO app",
        OptionB:"Quiz app",
        OptionC:"Food ordering app",
        OptionD:"Picture app",
        answer:"B",
    },
    {
        prompt: "React js uses what script?",
        OptionA:"Monoscript",
        OptionB:"Polyscript",
        OptionC:"Typescript",
        OptionD:"Javascript",
        answer:"D",
    },
];